apiVersion: v2
name: globex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: inventory-app
    version: 0.1.0
    repository: file://inventory-app
  - name: catalog-app
    version: 0.1.0
    repository: file://catalog-app
  - name: activity-tracking
    version: 0.1.0
    repository: file://activity-tracking
  - name: recommendation-engine
    version: 0.1.0
    repository: file://recommendation-engine
  - name: activity-tracking-simulator
    version: 0.1.0
    repository: file://activity-tracking-simulator
  - name: globex-ui
    version: 0.1.0
    repository: file://globex-ui
  - name: kafka-broker
    version: 0.1.0
    repository: file://kafka/kafka-broker
    condition: kafka.enabled 
  - name: kafdrop
    version: 0.1.0
    repository: file://kafka/kafdrop
    condition: kafka.enabled
